### ISSUE TITLE
hackage sdist is missing a file needed for testing

### ISSUE THREAD

**Issue by aavogt** [ghorn/dvda#36]
cabal test gives:
```
Preprocessing test suite 'test' for dvda-0.4...

TestMain.hs:9:8:
    Could not find module ‘Dvda.Tests.Unary’
    Use -v to see a list of the files searched for.
```

**Comment by ghorn** [comment]
That smells like code rot - this project is quasi deprecated in favor of https://github.com/ghorn/dynobud. I'll fix this though

**Comment by ghorn** [comment]
Fixing the missing file reveals the tests are broken. I'm closing this issue and adding deprecatoin notices on github and hackage in favor of dynobud
